### ISSUE TITLE
Warning: Failed prop type: The prop `onRequestClose` is marked as required in `Modal`, but its value is `undefined`.

### ISSUE THREAD

**Issue by Harryki** [hiddentao/react-native-modal-filter-picker#11]
Hello friends. 

Thanks for the awesome picker library. 

just tried your example on my project and encountered this warning message 

any thought about this?

**Comment by Harryki** [comment]
i added onRequestClose={this.props.onRequestClose} property in <Modal >component in line 47 
and passed property onRequestClose in my <ModalFilterPicker >.

you can close this issue.

**Comment by ducanhmai205** [comment]
i cant fix this issue, can u give more infomation abt this pls

**Comment by clementino36** [comment]
I have the same issue. Harryki fixed the warning by adding `onRequestClose={this.props.onRequestClose}` in the index.js of the library at line 47.
Can you implement it please ?

**Comment by daleshaney** [comment]
I tried to implement the fix given by Harryki, however I still get the error, even after putting onRequestClose={this.props.onRequestClose} in the index.js of the library at line 47. Is there something I am missing to fix this?
