### ISSUE TITLE
Add keyboardShouldPersistTaps="always" to ListView

### ISSUE THREAD

**Issue by clementino36** [hiddentao/react-native-modal-filter-picker#13]
When the Keyboard is shown and you click on an list item, you have to click twice (once for the keyboard to disappear, and then the actual item click).
Adding keyboardShouldPersistTaps="always" fixes this. Can you add it to the ListView or maybe as an optional prop to ModalFilterPicker ?
Thanks

**Comment by IdealSystemsMCP** [comment]
@clementino36 

You can set the ListView properties yourself with the property listViewProps. 
Example: 

<ModalFilterPicker
     listViewProps={{"keyboardShouldPersistTaps":"always"}}
     ....
/>

Kind regards

**Comment by clementino36** [comment]
My bad for not reading the docs more.
Great library, thank you!

**Comment by manjuy124** [comment]
<ModalFilterPicker
listViewProps={{keyboardShouldPersistTaps:"always"}}
....
/>

remove double quotes to get it work..
