### ISSUE TITLE
Warning: Failed prop type : The prop 'onRequestClose' is marked as required in modal but its value is undefined

### ISSUE THREAD

**Issue by rahulbhankar786** [hiddentao/react-native-modal-filter-picker#16]
![screenshot_1521534730](https://user-images.githubusercontent.com/33485869/37644174-f1ee50f2-2c48-11e8-8ae6-04b58c0e6193.png)

**Comment by Secchi1** [comment]
Hi, i had the same problem.

**Comment by Secchi1** [comment]
i have the solution, in the pluggin index.js i add on the modal this line. 
onRequestClose={()=>{}}.
i hope this will help you.

**Comment by Kassio-Barros** [comment]
tanks

**Comment by hiddentao** [comment]
This is a mandatory prop.

**Comment by barbier** [comment]
@Secchi1 You're the real MVP!
