### ISSUE TITLE
How can I using modal filter piker in tcomb-form-native

### ISSUE THREAD

**Issue by abdelghafourzguindou** [hiddentao/react-native-modal-filter-picker#2]

**Comment by hiddentao** [comment]
Hey, is this still an issue? What output do you get in the JS console?

**Comment by herarya** [comment]
![screen shot 2017-08-25 at 2 24 29 pm](https://user-images.githubusercontent.com/5027291/29703817-6c43b86a-89a1-11e7-8698-1a399107ff2a.png)
@zGuindouGit I try to use the code from you and edit, it runs fine

`ModalSelect.js

import React from 'react';
import { View, Text, StyleSheet } from 'react-native'
import SelectFiltring from './SelectFiltering';

function select(locals) {
  if (locals.hidden) {
    return null;
  }

  const stylesheet = locals.stylesheet;
  let formGroupStyle = stylesheet.formGroup.normal;
  let controlLabelStyle = stylesheet.controlLabel.normal;
  let selectStyle = stylesheet.select.normal;
  let helpBlockStyle = stylesheet.helpBlock.normal;
  let errorBlockStyle = stylesheet.errorBlock;

  if (locals.hasError) {
    formGroupStyle = stylesheet.formGroup.error;
    controlLabelStyle = stylesheet.controlLabel.error;
    selectStyle = stylesheet.select.error;
    helpBlockStyle = stylesheet.helpBlock.error;
  }

  const label = locals.label ? <Text style={controlLabelStyle}>{locals.label}</Text> : null;
  const help = locals.help ? <Text style={helpBlockStyle}>{locals.help}</Text> : null;
  const error = locals.hasError && locals.error ? <Text accessibilityLiveRegion="polite" style={errorBlockStyle}>{locals.error}</Text> : null;


  var options = [];
  
  getOptions = () => {
    locals.options.map(({value, text}) => {
      //<Picker.Item key={value} value={value} label={text} />
      options.push({key: text, label: text});
    });
  }

  setSelectedValue = (value) => {
    if(value) {
      locals.value = value;
      locals.hasError = false;
      locals.error = null;
    }
  }

  return (
         getOptions(),
        <View style={formGroupStyle}>
        {label}
        <SelectFiltring 
                    options={options} 
                    setSelectedValue={this.setSelectedValue.bind(this)}
                    locals={locals}
                    selectedValue={locals.value}
                />

        {help}
        {error}
        </View>
  );
}

const styles = StyleSheet.create({
  container: {
    borderWidth: 1,
    height: 50,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 9,
    backgroundColor: 'white'
  }
})

module.exports = select;

`
`
SelectFiltering.js
import React, { Component } from 'react';
import { View, Text, Picker, TouchableOpacity, StyleSheet, Dimensions,Image } from 'react-native'
import ModalFilterPicker from 'react-native-modal-filter-picker'
const { width, height } = Dimensions.get('window')
import { colors } from './../../StyleSheet';

export default class SelectFiltring extends Component {
    constructor(props, ctx) {
        super(props, ctx);

        this.state = {
            visible: false,
            picked: null,
        };
    }


    render() {
        const locals = this.props.locals;
        const { stylesheet } = locals;
        let pickerContainer = stylesheet.pickerContainer.normal;
        let pickerContainerOpen = stylesheet.pickerContainer.open;
        let selectStyle = stylesheet.select.normal;
        let touchableStyle = stylesheet.pickerTouchable.normal;
        let touchableStyleActive = stylesheet.pickerTouchable.active;
        let pickerValue = stylesheet.pickerValue.normal;
        if (locals.hasError) {
          pickerContainer = stylesheet.pickerContainer.error;
          selectStyle = stylesheet.select.error;
          touchableStyle = stylesheet.pickerTouchable.error;
          pickerValue = stylesheet.pickerValue.error;
        }

        const { visible, picked } = this.state;

        return (
            <View style={[pickerContainer]}>
                <TouchableOpacity style={[touchableStyle,{ flexDirection : 'row',
            justifyContent: 'space-between'}]} 
                    onPress={() => { this.onShow() }}>
                    <Text>{picked? picked: this.props.options[0].label}</Text>
                    <Image source={require('./../../../assets/images/arrowDown338.png')} />
                </TouchableOpacity>
                <ModalFilterPicker
                    visible={visible}
                    onSelect={(selectedPiked) => { this.onSelect(selectedPiked) }}
                    onCancel={() => { this.onCancel() }}
                    options={this.props.options}
                    placeholderText={'search item ...'}
                    cancelButtonText={'CLOSE'}
                    title={locals.label}
                    listContainerStyle={styles.listContainer}
                    cancelContainerStyle={styles.cancelContainer}
                    cancelButtonStyle={styles.cancelButton}
                    cancelButtonTextStyle={styles.cancelButtonText}
                />
            </View>
        );
    }

    onShow = () => {
        this.setState({ visible: true });
    }

    onSelect = (picked) => {
        this.setState({
            picked: picked,
            visible: false
        });
        this.props.selectedValue = picked;
        //alert(this.props.selectedValue);
        this.props.setSelectedValue(picked);
    }

    onCancel = () => {
        this.setState({
            visible: false
        });
    }
}
const optionStyle = {
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee'
  }
  
  const optionTextStyle = {
    flex: 1,
    textAlign: 'left',
    color: '#000',
    fontSize: 22
  }

const styles = StyleSheet.create({
    overlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.85)',
        justifyContent: 'center',
        alignItems: 'center'
      },
      titleTextStyle: {
        flex: 0,
        color: '#fff',
        fontSize: 20,
        marginBottom: 15
      },
      listContainer: {
        flex: 1,
        width: width * 0.8,
        maxHeight: height * 0.7,
        backgroundColor: '#fff',
        borderTopLeftRadius : 6,
        borderTopRightRadius : 6,
      },
      cancelContainer: {
        width: width * 0.8,
        height : 40,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor : 'white',
        borderBottomLeftRadius : 6,
        borderBottomRightRadius : 6,
      },
      cancelButton: {
        flex: 0,
        paddingVertical: 10,
        paddingHorizontal: 20,
        backgroundColor:'white'
      },
      cancelButtonText: {
        textAlign: 'center',
        fontWeight: "bold",
        fontSize: 18
      },
      filterTextInputContainer: {
        borderBottomWidth: 1,
        borderBottomColor: '#999'
      },
      filterTextInput: {
        paddingVertical: 10,
        paddingHorizontal: 15,
        flex: 0,
        height: 50
      },
      categoryStyle: {
        ...optionStyle
      },
      categoryTextStyle: {
        ...optionTextStyle,
        color: '#999',
        fontStyle: 'italic',
        fontSize: 16
      },
      optionStyle: {
        ...optionStyle
      },
      optionStyleLastChild: {
        borderBottomWidth: 0
      },
      optionTextStyle: {
        ...optionTextStyle
      },
      selectedOptionStyle: {
        ...optionStyle
      },
      selectedOptionStyleLastChild: {
        borderBottomWidth: 0
      },
      selectedOptionTextStyle: {
        ...optionTextStyle,
        fontWeight: '700'
      },
      noResults: {
        flex: 0,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 10
      },
      noResultsText: {
        flex: 1,
        textAlign: 'center',
        color: '#ccc',
        fontStyle: 'italic',
        fontSize: 22
      }
    
})`

![screen shot 2017-08-25 at 2 24 18 pm](https://user-images.githubusercontent.com/5027291/29703810-679ddeee-89a1-11e7-98b1-566572522654.png)

**Comment by zGuindouGit** [comment]
Thanks++ @herarya
