### ISSUE TITLE
what is call back function for label

### ISSUE THREAD

**Issue by minajm** [hiddentao/react-native-modal-filter-picker#6]
onSelect is Callback for when an option is chosen,
but just work for key , we nee a callback function for label?

**Comment by giginkrishnan** [comment]
Same for me, :( any way to get the label ?

**Comment by prashantvv** [comment]
labels were working few days agoas I used  
  onSelect = (picked,label) => {
  },
but now they are not working in the app.
may have to use a separate list with this. I you've found any solution, kindly add up here

**Comment by hiddentao** [comment]
@prashantvv thanks
